# Generated by Django 3.2.4 on 2022-06-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_remove_user_companyname'),
        ('posts', '0002_alter_posts_applicantid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantID', models.ForeignKey(db_column='ApplicantID', on_delete=django.db.models.deletion.CASCADE, to='login.applicant')),
                ('employerID', models.ForeignKey(db_column='EmployerID', on_delete=django.db.models.deletion.CASCADE, to='login.employer')),
                ('postID', models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
            options={
                'db_table': 'Match',
            },
        ),
    ]
