# Generated by Django 3.2.4 on 2021-06-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('isVerified', models.IntegerField()),
                ('isDeleted', models.IntegerField()),
                ('user_type', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employerUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('companyName', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
            ],
            options={
                'db_table': 'Employer',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('applicantUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'db_table': 'Applicant',
            },
        ),
    ]
