# Generated by Django 3.2.4 on 2021-06-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ratings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.rating'),
        ),
    ]
