# Generated by Django 3.2.4 on 2021-06-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_applicant_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companyName',
        ),
    ]
