# Generated by Django 3.2.4 on 2021-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('numOfRates', models.IntegerField()),
                ('raterEmail', models.ManyToManyField(to='login.Employer')),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
    ]
